insert into room(vacancy,type) values
("Available","general"),
("Available","general"),
("Available","general"),
("Available","general"),
("Available","general"),
("Not Available","general"),
("Not Available","general"),
("Not Available","general"),
("Not Available","semi special"),
("Not Available","semi special"),
("Not Available","semi special"),
("Not Available","semi special"),
("Not Available","semi special"),
("Not Available","semi special"),
("Not Available","semi special"),
("Not Available","semi special"),
("Available","semi special"),
("Available","semi special"),
("Available","semi special"),
("Available","special"),
("Available","special"),
("Available","special"),
("Available","special"),
("Available","special"),
("Not Available","special"),
("Not Available","special"),
("Not Available","special"),
("Not Available","ultra special"),
("Not Available","ultra special"),
("Available","ultra special"),
("Available","ultra special"),
("Available","ultra special"),
("Available","ultra special"),
("Not Available","ultra delux"),
("Available","ultra delux"),
("Available","ultra delux"),
("Available","ultra delux"),
("Available","ultra delux"),
("Not Available","maternity ward"),
("Not Available","maternity ward"),
("Not Available","maternity ward"),
("Not Available","maternity ward"),
("Available","maternity ward"),
("Available","maternity ward"),
("Not Available","ITU"),
("Available","ITU"),
("Available","ITU"),
("Available","NICU");




