insert into assigns(consult_no,test_name) values
(26,"X ray"),
(24,"Urine Culture tests"),
(10,"ECG"),
(30,"Complete Blood Count1"),
(14,"MRI"),
(35,"HbA1C"),
(8,"Stool Culture test"),
(38,"Ultrasound"),
(32,"Vdrl Test"),
(11,"ESR"),
(19,"CT Scan"),
(22,"X ray"),
(20,"Biopsy"),
(21,"Thyroid Function tests"),
(9,"Allergy Tests"),
(5,"Ultrasound"),
(40,"ECG"),
(3,"Tests For Blood Glucose"),
(38,"Kidney Function tests"),
(36,"Bone Density");

