insert into diagnosis(consult_no,problem) values
(1,"Cold"),
(2,"Hyperthyroidism"),
(3,"Fever"),
(4,"Hypertension"),
(5,"Jaundice"),
(6,"Headache"),
(7,"Arrhythmia"),
(8,"Worm Manifestations"),
(9,"Allergic to dust"),
(10,"Cardiac arrest"),
(11,"Aneamic"),
(12,"Viral fever"),
(13,"Low Blood Pressure"),
(14,"Pneumonia"),
(15,"Arthritis/joint swellings"),
(16,"Fever"),
(17,"Skin itch/eczema"),
(18,"Tuberculosis"),
(19,"Brain tumor"),
(20,"Breast tumor"),
(21,"Hyperthyroidism"),
(22,"Multiple Fracture"),
(23,"Premature baby birth"),
(24,"Urine Infection"),
(25,"Dengue"),
(26,"Gallstones in Gallbladder"),
(27,"Stroke"),
(28,"Headache"),
(29,"Cold and cough"),
(30,"Malaria"),
(31,"Ligment tear"),
(32,"Syphilis"),
(33,"Upper respiratory tract infection"),
(34,"BodyAche"),
(35,"Stage2 Diabetics"),
(36,"Osteoporesis"),
(37,"Healthy"),
(38,"Kidney failure"),
(39,"Hypertension"),
(40,"Congestive heart failure");


